packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@eslint/eslintrc@3.3.6>js-yaml": "4.3.2"
  "@hey-api/json-schema-ref-parser@1.4.4>js-yaml": "4.3.2"

allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: true
