"""Generate or check the committed Lumina OpenAPI client artifacts."""

from __future__ import annotations

import argparse
import ctypes
import errno
import hashlib
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Protocol, cast
from uuid import uuid4

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[2]
CLIENT_ROOT: Final = REPOSITORY_ROOT / "packages" / "api-client"
CANONICAL_ARTIFACTS: Final = {
    Path("openapi/openapi.json"): CLIENT_ROOT / "openapi" / "openapi.json",
    Path("src/generated/types.gen.ts"): CLIENT_ROOT / "src" / "generated" / "types.gen.ts",
    Path("src/generated/zod.gen.ts"): CLIENT_ROOT / "src" / "generated" / "zod.gen.ts",
}
_GENERATED_NAMES: Final = frozenset({"types.gen.ts", "zod.gen.ts"})
_EXPECTED_TYPE_SYMBOLS: Final = frozenset(
    {
        "ClientOptions",
        "CompactSourceReference",
        "CurrentCanonicalSelectionResponse",
        "CurrentSelectionReference",
        "DatasetReference",
        "EntityBrowsePageResponse",
        "EntityDetailResponse",
        "EntityQuantityResponse",
        "EntitySummaryResponse",
        "EntityType",
        "ErrorBody",
        "ErrorResponse",
        "FeatureFlags",
        "GetCatalogEntityData",
        "GetCatalogEntityError",
        "GetCatalogEntityErrors",
        "GetCatalogEntityResponse",
        "GetCatalogEntityResponses",
        "GetCatalogEntityBySlugData",
        "GetCatalogEntityBySlugError",
        "GetCatalogEntityBySlugErrors",
        "GetCatalogEntityBySlugResponse",
        "GetCatalogEntityBySlugResponses",
        "GetSourceRecordProvenanceData",
        "GetSourceRecordProvenanceError",
        "GetSourceRecordProvenanceErrors",
        "GetSourceRecordProvenanceResponse",
        "GetSourceRecordProvenanceResponses",
        "HistorySelectionReference",
        "ListCatalogEntityCanonicalSelectionsData",
        "ListCatalogEntityCanonicalSelectionsError",
        "ListCatalogEntityCanonicalSelectionsErrors",
        "ListCatalogEntityCanonicalSelectionsResponse",
        "ListCatalogEntityCanonicalSelectionsResponses",
        "ListCatalogEntityMeasurementsData",
        "ListCatalogEntityMeasurementsError",
        "ListCatalogEntityMeasurementsErrors",
        "ListCatalogEntityMeasurementsResponse",
        "ListCatalogEntityMeasurementsResponses",
        "ListCatalogEntitiesData",
        "ListCatalogEntitiesError",
        "ListCatalogEntitiesErrors",
        "ListCatalogEntitiesResponse",
        "ListCatalogEntitiesResponses",
        "LiveHealthLiveGetData",
        "LiveHealthLiveGetResponse",
        "LiveHealthLiveGetResponses",
        "LiveResponse",
        "MeasurementPageResponse",
        "MeasurementReference",
        "MeasurementResponse",
        "MetaResponse",
        "MetadataApiV1MetaGetData",
        "MetadataApiV1MetaGetResponse",
        "MetadataApiV1MetaGetResponses",
        "PageResponse",
        "ProviderReference",
        "QuantityReference",
        "ReadyHealthReadyGetData",
        "ReadyHealthReadyGetResponse",
        "ReadyHealthReadyGetResponses",
        "ReadyResponse",
        "SelectionHistoryPageResponse",
        "SelectionHistoryResponse",
        "SelectionState",
        "SourceDatasetResponse",
        "SourceProvenanceResponse",
        "SourceProviderResponse",
        "SourceRecordResponse",
        "UnitReference",
    }
)
_EXPECTED_ZOD_SYMBOLS: Final = frozenset(
    {
        "zCompactSourceReference",
        "zCurrentCanonicalSelectionResponse",
        "zCurrentSelectionReference",
        "zDatasetReference",
        "zEntityBrowsePageResponse",
        "zEntityDetailResponse",
        "zEntityQuantityResponse",
        "zEntitySummaryResponse",
        "zEntityType",
        "zErrorBody",
        "zErrorResponse",
        "zFeatureFlags",
        "zGetCatalogEntityResponse",
        "zGetCatalogEntityBySlugResponse",
        "zGetSourceRecordProvenanceResponse",
        "zHistorySelectionReference",
        "zLiveHealthLiveGetResponse",
        "zLiveResponse",
        "zMeasurementPageResponse",
        "zMeasurementReference",
        "zMeasurementResponse",
        "zMetaResponse",
        "zPageResponse",
        "zProviderReference",
        "zQuantityReference",
        "zMetadataApiV1MetaGetResponse",
        "zReadyHealthReadyGetResponse",
        "zReadyResponse",
        "zSelectionHistoryPageResponse",
        "zSelectionHistoryResponse",
        "zSelectionState",
        "zSourceDatasetResponse",
        "zSourceProvenanceResponse",
        "zSourceProviderResponse",
        "zSourceRecordResponse",
        "zUnitReference",
        "zListCatalogEntityCanonicalSelectionsResponse",
        "zListCatalogEntityMeasurementsResponse",
        "zListCatalogEntitiesResponse",
    }
)
_AUTOGENERATED_BANNER: Final = "// This file is auto-generated by @hey-api/openapi-ts"
_AT_FDCWD: Final = -100
_RENAME_NOREPLACE: Final = 1
_RENAME_EXCHANGE: Final = 2


class GenerationError(RuntimeError):
    """Raised when temporary generation violates the committed-artifact contract."""


class SafePublicationError(GenerationError):
    """A fixed publication failure that is safe to emit without a traceback."""


class PartialCanonicalSetError(SafePublicationError):
    """Raised when only part of the canonical artifact set exists."""

    def __init__(self) -> None:
        super().__init__("Lumina API client canonical artifact set is incomplete.")


class PublicationConcurrencyError(SafePublicationError):
    """Raised when canonical bytes change after the publication baseline."""

    def __init__(self) -> None:
        super().__init__("Lumina API client publication detected a concurrent change.")


class PublicationRecoveryError(SafePublicationError):
    """Raised when publication recovery cannot be completed and verified."""

    def __init__(self) -> None:
        super().__init__("Lumina API client publication requires recovery.")


class PublicationPrimitiveError(SafePublicationError):
    """Raised when safe atomic publication is unavailable."""

    def __init__(self) -> None:
        super().__init__("Lumina API client atomic publication is unavailable.")


class PublicationOperationError(SafePublicationError):
    """Raised when an ordinary publication operation fails after safe recovery."""

    def __init__(self) -> None:
        super().__init__("Lumina API client publication failed.")


@dataclass(frozen=True)
class Publication:
    """One fully validated artifact ready for canonical publication."""

    destination: Path
    content: bytes


class _RenameAt2Function(Protocol):
    argtypes: list[object]
    restype: object

    def __call__(
        self,
        old_directory: int,
        old_path: bytes,
        new_directory: int,
        new_path: bytes,
        flags: int,
    ) -> int: ...


_AtomicRename = Callable[[Path, Path, int], None]


@dataclass(frozen=True)
class _RollbackOutcome:
    baseline_restored: bool
    conflict_retained: bool


def _run(command: Sequence[str], *, cwd: Path = REPOSITORY_ROOT) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def _validate_openapi(content: bytes) -> None:
    if not content.endswith(b"\n") or b"\r" in content:
        raise GenerationError("OpenAPI output violates the LF/trailing-newline contract")
    if content.startswith(b'{\n  "components"') is False:
        raise GenerationError("OpenAPI output is not stable sorted, indented JSON")
    required_paths = (
        b'"/api/v1/meta"',
        b'"/health/live"',
        b'"/health/ready"',
        b'"/api/v1/catalog/entities"',
        b'"/api/v1/catalog/entities/by-slug/{slug}"',
        b'"/api/v1/catalog/entities/{entity_id}"',
        b'"/api/v1/catalog/entities/{entity_id}/measurements"',
        b'"/api/v1/catalog/entities/{entity_id}/canonical-selections"',
        b'"/api/v1/catalog/sources/{source_record_id}"',
        b'"get_catalog_entity"',
        b'"list_catalog_entities"',
        b'"get_catalog_entity_by_slug"',
        b'"list_catalog_entity_measurements"',
        b'"list_catalog_entity_canonical_selections"',
        b'"get_source_record_provenance"',
    )
    if any(path not in content for path in required_paths) or b'"/api/v1/sources/' in content:
        raise GenerationError("OpenAPI output is missing a required committed route")


def _validate_generated_files(output: Path) -> None:
    emitted = {str(path.relative_to(output)) for path in output.rglob("*") if path.is_file()}
    if emitted != _GENERATED_NAMES:
        raise GenerationError(
            f"generator emitted unexpected files: expected {sorted(_GENERATED_NAMES)}, "
            f"received {sorted(emitted)}"
        )

    for name in _GENERATED_NAMES:
        text = (output / name).read_text(encoding="utf-8")
        if text.splitlines()[0] != _AUTOGENERATED_BANNER:
            raise GenerationError(f"{name} has an unexpected generated banner")
        if re.search(r"generated (?:at|on)|timestamp", text, flags=re.IGNORECASE):
            raise GenerationError(f"{name} contains volatile generated metadata")

    types_text = (output / "types.gen.ts").read_text(encoding="utf-8")
    type_symbols = frozenset(re.findall(r"export type ([A-Za-z0-9]+) =", types_text))
    if type_symbols != _EXPECTED_TYPE_SYMBOLS:
        raise GenerationError(
            "generated TypeScript symbols differ from the pinned preflight: "
            f"expected {sorted(_EXPECTED_TYPE_SYMBOLS)}, received {sorted(type_symbols)}"
        )
    if re.search(r"^import ", types_text, flags=re.MULTILINE) is not None:
        raise GenerationError("generated TypeScript imports differ from the pinned preflight")

    zod_text = (output / "zod.gen.ts").read_text(encoding="utf-8")
    zod_symbols = frozenset(re.findall(r"export const (z[A-Za-z0-9]+) =", zod_text))
    if zod_symbols != _EXPECTED_ZOD_SYMBOLS:
        raise GenerationError(
            "generated Zod symbols differ from the pinned preflight: "
            f"expected {sorted(_EXPECTED_ZOD_SYMBOLS)}, received {sorted(zod_symbols)}"
        )
    if re.search(r"import \* as z from [\"']zod[\"'];", zod_text) is None:
        raise GenerationError("generated Zod imports differ from the pinned preflight")


def _compile_and_probe(output: Path, workspace: Path) -> None:
    node_modules = workspace / "node_modules"
    node_modules.symlink_to(CLIENT_ROOT / "node_modules", target_is_directory=True)
    compiled = workspace / "compiled"
    compiled.mkdir()
    _run(
        (
            "pnpm",
            "--filter",
            "@lumina/api-client",
            "exec",
            "tsc",
            "--ignoreConfig",
            "--strict",
            "--target",
            "ES2024",
            "--module",
            "NodeNext",
            "--moduleResolution",
            "NodeNext",
            "--skipLibCheck",
            "--outDir",
            str(compiled),
            str(output / "types.gen.ts"),
            str(output / "zod.gen.ts"),
        )
    )
    (compiled / "node_modules").symlink_to(CLIENT_ROOT / "node_modules", target_is_directory=True)
    probe = """
const schemas = require(process.argv[1]);
const samples = [
  [schemas.zLiveResponse, {status: "live"}],
  [schemas.zReadyResponse, {status: "ready"}],
  [schemas.zMetaResponse, {
    api_version: "v1",
    application_name: "Lumina",
    application_version: "0.0.0",
    build_commit: null,
    feature_flags: {},
  }],
  [schemas.zFeatureFlags, {}],
];
if (samples.some(([schema, value]) => !schema?.safeParse(value).success)) process.exit(1);
if (schemas.zLiveResponse.safeParse({status: 42}).success) process.exit(2);
if (schemas.zFeatureFlags.safeParse({unexpected: true}).success) process.exit(3);
const parsed = schemas.zLiveResponse.parse({status: "live", unexpected: true});
if (Object.hasOwn(parsed, "unexpected")) process.exit(4);
const decimalSchemas = [
  schemas.zMeasurementReference?.shape?.value,
  schemas.zMeasurementResponse?.shape?.value,
];
const validDecimals = [
  "1.2300",
  "-0",
  "-0.0000",
  "1234567890123456789012345678901234567890",
  "0.0000000000000000000000000001",
  "1E-27",
];
const invalidDecimals = [1.23, "NaN", "Infinity", "-Infinity", "01", "1.", ".1", "1e"];
if (decimalSchemas.some((schema) =>
  validDecimals.some((value) => !schema?.safeParse(value).success)
)) process.exit(5);
if (decimalSchemas.some((schema) =>
  invalidDecimals.some((value) => schema.safeParse(value).success)
)) process.exit(6);
"""
    _run(("node", "-e", probe, str(compiled / "zod.gen.js")))


def _generate_once(workspace: Path) -> dict[Path, bytes]:
    openapi = workspace / "openapi.json"
    output = workspace / "generated"
    _run((sys.executable, "-m", "lumina.openapi_export", "--output", str(openapi)))
    _validate_openapi(openapi.read_bytes())
    _run(
        (
            "node",
            str(CLIENT_ROOT / "scripts" / "generate.mjs"),
            str(openapi),
            str(output),
        )
    )
    _validate_generated_files(output)
    _run(
        (
            "pnpm",
            "exec",
            "prettier",
            "--config",
            str(REPOSITORY_ROOT / "prettier.config.mjs"),
            "--write",
            str(output / "types.gen.ts"),
            str(output / "zod.gen.ts"),
        )
    )
    _validate_generated_files(output)
    _compile_and_probe(output, workspace)
    return {
        Path("openapi/openapi.json"): openapi.read_bytes(),
        Path("src/generated/types.gen.ts"): (output / "types.gen.ts").read_bytes(),
        Path("src/generated/zod.gen.ts"): (output / "zod.gen.ts").read_bytes(),
    }


def generate_validated_artifacts() -> dict[Path, bytes]:
    """Run two isolated generations and return only a byte-identical artifact set."""
    with tempfile.TemporaryDirectory(prefix="lumina-api-client-first-") as first_directory:
        first = _generate_once(Path(first_directory))
        with tempfile.TemporaryDirectory(prefix="lumina-api-client-second-") as second_directory:
            second = _generate_once(Path(second_directory))
    if first.keys() != second.keys():
        raise GenerationError("isolated generations emitted different artifact sets")
    mismatched = [path for path in first if first[path] != second[path]]
    if mismatched:
        raise GenerationError(
            f"isolated generations are not byte-identical: {[str(path) for path in mismatched]}"
        )
    return first


def _load_linux_renameat2() -> _AtomicRename:
    """Load Linux renameat2 without providing an unsafe fallback."""
    if sys.platform != "linux":
        raise PublicationPrimitiveError
    try:
        library = ctypes.CDLL(None, use_errno=True)
        function = cast(_RenameAt2Function, library.renameat2)
    except (AttributeError, OSError):
        raise PublicationPrimitiveError from None
    function.argtypes = [
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_uint,
    ]
    function.restype = ctypes.c_int

    def rename(source: Path, destination: Path, flags: int) -> None:
        ctypes.set_errno(0)
        result = function(
            _AT_FDCWD,
            os.fsencode(source),
            _AT_FDCWD,
            os.fsencode(destination),
            flags,
        )
        if result != 0:
            error_number = ctypes.get_errno() or errno.EIO
            raise OSError(error_number, "atomic rename failed") from None

    return rename


def _verify_atomic_publication_primitives(parent: Path, rename: _AtomicRename) -> None:
    """Prove both required renameat2 flags on one destination filesystem."""
    probe = uuid4().hex
    exchange_left = parent / f".lumina-renameat2-{probe}.exchange-left"
    exchange_right = parent / f".lumina-renameat2-{probe}.exchange-right"
    no_replace_source = parent / f".lumina-renameat2-{probe}.noreplace-source"
    no_replace_destination = parent / f".lumina-renameat2-{probe}.noreplace-destination"
    refusal_source = parent / f".lumina-renameat2-{probe}.refusal-source"
    refusal_destination = parent / f".lumina-renameat2-{probe}.refusal-destination"
    paths = (
        exchange_left,
        exchange_right,
        no_replace_source,
        no_replace_destination,
        refusal_source,
        refusal_destination,
    )
    owned: set[Path] = set()

    def create(path: Path, content: bytes) -> None:
        with path.open("xb") as handle:
            owned.add(path)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())

    try:
        create(exchange_left, b"left")
        create(exchange_right, b"right")
        rename(exchange_left, exchange_right, _RENAME_EXCHANGE)
        if exchange_left.read_bytes() != b"right" or exchange_right.read_bytes() != b"left":
            raise OSError(errno.EIO, "atomic exchange verification failed")

        create(no_replace_source, b"source")
        rename(no_replace_source, no_replace_destination, _RENAME_NOREPLACE)
        owned.remove(no_replace_source)
        owned.add(no_replace_destination)
        if no_replace_source.exists() or no_replace_destination.read_bytes() != b"source":
            raise OSError(errno.EIO, "atomic no-replace verification failed")

        create(refusal_source, b"refusal-source")
        create(refusal_destination, b"refusal-destination")
        try:
            rename(refusal_source, refusal_destination, _RENAME_NOREPLACE)
        except OSError as error:
            if error.errno != errno.EEXIST:
                raise
        else:
            raise OSError(errno.EIO, "atomic no-replace refusal failed")
        if (
            refusal_source.read_bytes() != b"refusal-source"
            or refusal_destination.read_bytes() != b"refusal-destination"
        ):
            raise OSError(errno.EIO, "atomic no-replace preservation failed")
    except Exception:
        raise PublicationPrimitiveError from None
    finally:
        cleanup_failed = False
        for path in paths:
            if path not in owned:
                continue
            try:
                path.unlink(missing_ok=True)
            except OSError:
                cleanup_failed = True
        if cleanup_failed:
            raise PublicationPrimitiveError from None


def publish_artifacts(
    publications: Sequence[Publication],
    *,
    before_replace: Callable[[int, Path], None] | None = None,
    before_atomic_publish: Callable[[int, Path], None] | None = None,
    after_publish: Callable[[int, Path], None] | None = None,
    before_restore: Callable[[int, Path], None] | None = None,
    renameat2_loader: Callable[[], _AtomicRename] | None = None,
) -> None:
    """Publish one canonical set with Linux pathname-atomic conflict preservation."""
    if len(publications) != len(CANONICAL_ARTIFACTS) or any(
        not item.content for item in publications
    ):
        raise GenerationError("publication requires a complete non-empty artifact set")
    destinations = [item.destination for item in publications]
    if len(set(destinations)) != len(destinations):
        raise GenerationError("publication destinations must be unique")

    baseline: dict[Path, bytes | None] = {}
    try:
        for destination in destinations:
            if not destination.exists():
                baseline[destination] = None
            elif destination.is_file():
                baseline[destination] = destination.read_bytes()
            else:
                raise PartialCanonicalSetError
    except PartialCanonicalSetError:
        raise
    except Exception:
        raise PublicationOperationError from None
    present_count = sum(content is not None for content in baseline.values())
    if present_count not in (0, len(publications)):
        raise PartialCanonicalSetError

    try:
        atomic_rename = (renameat2_loader or _load_linux_renameat2)()
    except PublicationPrimitiveError:
        raise
    except Exception:
        raise PublicationPrimitiveError from None

    parents = {destination.parent for destination in destinations}
    for parent in parents:
        if not parent.is_dir():
            raise PublicationPrimitiveError
        _verify_atomic_publication_primitives(parent, atomic_rename)

    transaction = uuid4().hex
    staged: dict[Path, Path] = {}
    backups: dict[Path, Path | None] = {}
    published: list[Path] = []
    recovery_artifacts: list[Path] = []
    intended = {item.destination: item.content for item in publications}

    def current_state(destination: Path) -> bytes | None:
        if not destination.exists():
            return None
        if not destination.is_file():
            raise OSError("canonical artifact is not a regular file")
        return destination.read_bytes()

    def cleanup_recovery_artifacts() -> None:
        for stage in staged.values():
            stage.unlink(missing_ok=True)
        for backup in backups.values():
            if backup is not None:
                backup.unlink(missing_ok=True)
        for recovery in recovery_artifacts:
            recovery.unlink(missing_ok=True)

    def complete_state() -> dict[Path, bytes | None]:
        return {destination: current_state(destination) for destination in destinations}

    def verify_transaction_state() -> None:
        expected = dict(baseline)
        for destination in published:
            expected[destination] = intended[destination]
        actual = complete_state()
        if actual == expected:
            return
        if any(actual[destination] != intended[destination] for destination in published):
            raise PublicationRecoveryError
        raise PublicationConcurrencyError

    def retain_conflict(source: Path, destination: Path, restore_index: int) -> Path:
        recovery = destination.with_name(
            f".{destination.name}.{transaction}.conflict-{restore_index}"
        )
        atomic_rename(source, recovery, _RENAME_NOREPLACE)
        recovery_artifacts.append(recovery)
        return recovery

    def rollback() -> _RollbackOutcome:
        """Atomically restore owned paths while retaining every displaced conflict."""
        conflict_retained = False
        for restore_index, destination in enumerate(reversed(published), start=1):
            if before_restore is not None:
                before_restore(restore_index, destination)
            stage = staged[destination]
            old_content = baseline[destination]
            if old_content is None:
                recovery = destination.with_name(
                    f".{destination.name}.{transaction}.rollback-{restore_index}"
                )
                atomic_rename(destination, recovery, _RENAME_NOREPLACE)
                recovery_artifacts.append(recovery)
                if current_state(recovery) != intended[destination]:
                    conflict_retained = True
                continue

            atomic_rename(stage, destination, _RENAME_EXCHANGE)
            if current_state(destination) != old_content:
                atomic_rename(stage, destination, _RENAME_EXCHANGE)
                raise OSError("atomic rollback displaced unexpected recovery bytes")
            displaced = current_state(stage)
            if displaced != intended[destination]:
                retain_conflict(stage, destination, restore_index)
                conflict_retained = True

        actual = complete_state()
        return _RollbackOutcome(
            baseline_restored=actual == baseline,
            conflict_retained=conflict_retained,
        )

    try:
        for item in publications:
            stage = item.destination.with_name(f".{item.destination.name}.{transaction}.new")
            with stage.open("xb") as handle:
                staged[item.destination] = stage
                handle.write(item.content)
                handle.flush()
                os.fsync(handle.fileno())

        for destination, old_content in baseline.items():
            if old_content is not None:
                backup = destination.with_name(f".{destination.name}.{transaction}.bak")
                with backup.open("xb") as handle:
                    backups[destination] = backup
                    handle.write(old_content)
                    handle.flush()
                    os.fsync(handle.fileno())
            else:
                backups[destination] = None

        for index, item in enumerate(publications, start=1):
            if before_replace is not None:
                before_replace(index, item.destination)
            if current_state(item.destination) != baseline[item.destination]:
                raise PublicationConcurrencyError
            if before_atomic_publish is not None:
                before_atomic_publish(index, item.destination)

            stage = staged[item.destination]
            if baseline[item.destination] is None:
                try:
                    atomic_rename(stage, item.destination, _RENAME_NOREPLACE)
                except OSError as error:
                    if error.errno == errno.EEXIST:
                        raise PublicationConcurrencyError from None
                    raise PublicationRecoveryError from None
            else:
                try:
                    atomic_rename(stage, item.destination, _RENAME_EXCHANGE)
                except OSError:
                    raise PublicationRecoveryError from None
                displaced = current_state(stage)
                if displaced != baseline[item.destination]:
                    try:
                        atomic_rename(stage, item.destination, _RENAME_EXCHANGE)
                    except OSError:
                        raise PublicationRecoveryError from None
                    if (
                        current_state(item.destination) != displaced
                        or current_state(stage) != intended[item.destination]
                    ):
                        raise PublicationRecoveryError
                    raise PublicationConcurrencyError

            published.append(item.destination)
            if after_publish is not None:
                after_publish(index, item.destination)
            verify_transaction_state()

        if complete_state() != intended:
            raise PublicationRecoveryError
        if complete_state() != intended:
            raise PublicationRecoveryError
    except BaseException as publication_error:
        try:
            rollback_outcome = rollback()
        except BaseException:
            raise PublicationRecoveryError from None
        if isinstance(publication_error, PublicationRecoveryError):
            raise PublicationRecoveryError from None
        if rollback_outcome.conflict_retained:
            raise PublicationRecoveryError from None
        if not rollback_outcome.baseline_restored:
            raise PublicationConcurrencyError from None
        try:
            cleanup_recovery_artifacts()
        except BaseException:
            raise PublicationRecoveryError from None
        if isinstance(publication_error, Exception) and not isinstance(
            publication_error, SafePublicationError
        ):
            raise PublicationOperationError from None
        raise publication_error
    else:
        try:
            cleanup_recovery_artifacts()
        except BaseException:
            raise PublicationRecoveryError from None


def _publications(artifacts: Mapping[Path, bytes]) -> list[Publication]:
    if set(artifacts) != set(CANONICAL_ARTIFACTS):
        raise GenerationError("validated artifact set is incomplete")
    return [
        Publication(destination=CANONICAL_ARTIFACTS[path], content=artifacts[path])
        for path in CANONICAL_ARTIFACTS
    ]


def stale_artifacts(
    artifacts: Mapping[Path, bytes],
    canonical_artifacts: Mapping[Path, Path] = CANONICAL_ARTIFACTS,
) -> list[str]:
    """Describe only generated artifacts whose canonical bytes are missing or stale."""
    stale: list[str] = []
    for relative, canonical in canonical_artifacts.items():
        actual = canonical.read_bytes() if canonical.is_file() else b""
        expected = artifacts[relative]
        if actual != expected:
            actual_hash = hashlib.sha256(actual).hexdigest() if actual else "missing"
            expected_hash = hashlib.sha256(expected).hexdigest()
            stale.append(f"{relative} (committed={actual_hash}, expected={expected_hash})")
    return stale


def _generate() -> int:
    artifacts = generate_validated_artifacts()
    publish_artifacts(_publications(artifacts))
    print("api:generate: published 3 validated, byte-identical artifacts")
    return 0


def _check() -> int:
    artifacts = generate_validated_artifacts()
    stale = stale_artifacts(artifacts)
    if stale:
        print("api:check: generated artifacts are stale:", file=sys.stderr)
        for detail in stale:
            print(f"  {detail}", file=sys.stderr)
        print("Run `pnpm api:generate` and review only those artifacts.", file=sys.stderr)
        return 1
    print("api:check: 3 committed artifacts are current and deterministic")
    return 0


def main(arguments: Sequence[str] | None = None) -> int:
    """Run the requested generated-artifact operation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("operation", choices=("check", "generate"))
    operation = parser.parse_args(arguments).operation
    try:
        return _check() if operation == "check" else _generate()
    except SafePublicationError as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
